spring:
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: changelog/db.changelog-master.xml
    drop-first: false
logging:
  level:
    com.querydsl.jpa: DEBUG
    log4j.logger.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
